//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBaseline) DeepCopyInto(out *ClusterBaseline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBaseline.
func (in *ClusterBaseline) DeepCopy() *ClusterBaseline {
	if in == nil {
		return nil
	}
	out := new(ClusterBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterBaseline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBaselineList) DeepCopyInto(out *ClusterBaselineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterBaseline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBaselineList.
func (in *ClusterBaselineList) DeepCopy() *ClusterBaselineList {
	if in == nil {
		return nil
	}
	out := new(ClusterBaselineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterBaselineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBaselineSpec) DeepCopyInto(out *ClusterBaselineSpec) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ProfileKey, len(*in))
		copy(*out, *in)
	}
	if in.TailoredProfiles != nil {
		in, out := &in.TailoredProfiles, &out.TailoredProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Console = in.Console
	out.Remediation = in.Remediation
	out.Scoring = in.Scoring
	if in.Waivers != nil {
		in, out := &in.Waivers, &out.Waivers
		*out = make([]WaiverEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBaselineSpec.
func (in *ClusterBaselineSpec) DeepCopy() *ClusterBaselineSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterBaselineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBaselineStatus) DeepCopyInto(out *ClusterBaselineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(int32)
		**out = **in
	}
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.NextScanTime != nil {
		in, out := &in.NextScanTime, &out.NextScanTime
		*out = (*in).DeepCopy()
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ProfileStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TailoredProfiles != nil {
		in, out := &in.TailoredProfiles, &out.TailoredProfiles
		*out = make([]TailoredProfileStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]ScoreSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelatedObjects != nil {
		in, out := &in.RelatedObjects, &out.RelatedObjects
		*out = make([]ObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.NewlyFailed != nil {
		in, out := &in.NewlyFailed, &out.NewlyFailed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Fixed != nil {
		in, out := &in.Fixed, &out.Fixed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreviousFailures != nil {
		in, out := &in.PreviousFailures, &out.PreviousFailures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBaselineStatus.
func (in *ClusterBaselineStatus) DeepCopy() *ClusterBaselineStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterBaselineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleSpec) DeepCopyInto(out *ConsoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleSpec.
func (in *ConsoleSpec) DeepCopy() *ConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileStatus) DeepCopyInto(out *ProfileStatus) {
	*out = *in
	if in.ProfileNames != nil {
		in, out := &in.ProfileNames, &out.ProfileNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ResultCounts = in.ResultCounts
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]ScoreSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileStatus.
func (in *ProfileStatus) DeepCopy() *ProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultCounts) DeepCopyInto(out *ResultCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultCounts.
func (in *ResultCounts) DeepCopy() *ResultCounts {
	if in == nil {
		return nil
	}
	out := new(ResultCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoreSnapshot) DeepCopyInto(out *ScoreSnapshot) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoreSnapshot.
func (in *ScoreSnapshot) DeepCopy() *ScoreSnapshot {
	if in == nil {
		return nil
	}
	out := new(ScoreSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoringSpec) DeepCopyInto(out *ScoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoringSpec.
func (in *ScoringSpec) DeepCopy() *ScoringSpec {
	if in == nil {
		return nil
	}
	out := new(ScoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailoredProfileStatus) DeepCopyInto(out *TailoredProfileStatus) {
	*out = *in
	out.ResultCounts = in.ResultCounts
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]ScoreSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailoredProfileStatus.
func (in *TailoredProfileStatus) DeepCopy() *TailoredProfileStatus {
	if in == nil {
		return nil
	}
	out := new(TailoredProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaiverEntry) DeepCopyInto(out *WaiverEntry) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.ReviewBy != nil {
		in, out := &in.ReviewBy, &out.ReviewBy
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaiverEntry.
func (in *WaiverEntry) DeepCopy() *WaiverEntry {
	if in == nil {
		return nil
	}
	out := new(WaiverEntry)
	in.DeepCopyInto(out)
	return out
}
