---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseline-security-operator
rules:
- apiGroups:
  - ""
  resourceNames:
  - baseline-security-compliance-dashboard
  resources:
  - configmaps
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - baseline-security-console-plugin
  resources:
  - services
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - baseline-security-console-plugin
  resources:
  - deployments
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - baselinesecurity.openshift.io
  resources:
  - clusterbaselines
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baselinesecurity.openshift.io
  resources:
  - clusterbaselines/finalizers
  verbs:
  - update
- apiGroups:
  - baselinesecurity.openshift.io
  resources:
  - clusterbaselines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancecheckresults
  - compliancescans
  - compliancesuites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettings
  verbs:
  - create
- apiGroups:
  - compliance.openshift.io
  resourceNames:
  - baseline
  resources:
  - scansettings
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resourceNames:
  - cluster
  resources:
  - infrastructures
  verbs:
  - get
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resourceNames:
  - baseline-security-console-plugin
  resources:
  - consoleplugins
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - patch
- apiGroups:
  - operator.openshift.io
  resourceNames:
  - cluster
  resources:
  - consoles
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - create
  - list
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - compliance-operator
  resources:
  - operatorgroups
  - subscriptions
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - policy
  resourceNames:
  - baseline-security-console-plugin
  resources:
  - poddisruptionbudgets
  verbs:
  - delete
  - get
  - patch
  - update
