---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baseline-security-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baselinesecurity.io
  resources:
  - clusterbaselines
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baselinesecurity.io
  resources:
  - clusterbaselines/finalizers
  verbs:
  - update
- apiGroups:
  - baselinesecurity.io
  resources:
  - clusterbaselines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancecheckresults
  - compliancescans
  - compliancesuites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings
  - scansettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
