apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: baseline-security-operator
  labels:
    app: baseline-security-operator
spec:
  selector:
    matchLabels:
      app: baseline-security-operator
      control-plane: controller-manager
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: 30s
      tlsConfig:
        serverName: baseline-security-operator-metrics.openshift-baseline-security.svc
        ca:
          configMap:
            name: baseline-security-metrics-serving-ca
            key: service-ca.crt
      authorization:
        type: Bearer
        credentials:
          name: baseline-security-metrics-scraper-token
          key: token
