apiVersion: v1
kind: Secret
metadata:
  name: baseline-security-metrics-scraper-token
  annotations:
    kubernetes.io/service-account.name: baseline-security-metrics-scraper
type: kubernetes.io/service-account-token
